name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace secrets
        run: |
          sed -i "s|__APP_PASSWORD__|${{ secrets.APP_PASSWORD }}|g" index.html
          sed -i "s|__API_KEY__|${{ secrets.API_KEY }}|g" firebase.js
          sed -i "s|__AUTH_DOMAIN__|${{ secrets.AUTH_DOMAIN }}|g" firebase.js
          sed -i "s|__PROJECT_ID__|${{ secrets.PROJECT_ID }}|g" firebase.js
          sed -i "s|__STORAGE_BUCKET__|${{ secrets.STORAGE_BUCKET }}|g" firebase.js
          sed -i "s|__MESSAGING_SENDER_ID__|${{ secrets.MESSAGING_SENDER_ID }}|g" firebase.js
          sed -i "s|__APP_ID__|${{ secrets.APP_ID }}|g" firebase.js
          sed -i "s|__MEASUREMENT_ID__|${{ secrets.MEASUREMENT_ID }}|g" firebase.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
